# Generated by Django 5.1.4 on 2025-04-08 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0002_pedido_itempedido"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="ItemPedido",
        ),
        migrations.DeleteModel(
            name="Pedido",
        ),
    ]
