# Generated by Django 5.1.4 on 2025-04-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0004_alter_produto_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="produto_imagens/%Y/%m"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
